# Generated by Django 4.2.4 on 2024-07-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('current_word', models.CharField(blank=True, max_length=100, null=True)),
                ('timer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('avatar', models.CharField(max_length=10000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='room.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='current_drawer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawer', to='room.user'),
        ),
    ]
