# Generated by Django 5.0.6 on 2024-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_room_id_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.CharField(
                editable=False, max_length=16, primary_key=True, serialize=False
            ),
        ),
    ]
